### ISSUE TITLE
error `run_command`

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/0D#3]
Hi 
I don't know if this affects you but this procedure `run_command` does not exist

<img width="557" alt="image" src="https://github.com/guitarvydas/0D/assets/214189/f688bd2b-9bfd-4fc1-85a3-2ffb950dfbe7">

**Comment by guitarvydas** [comment]
`run_command` is needed. If it is missing, then, that's a bug / oversight. I would have expected to find it in 0D/python/process.py. This should be a no-brainer in Python (it's not a no-brainer in Odin, though). I would guess that this is almost a 1-liner in Python. The only nuance is that we have to capture stdout and stderr and return them as strings. Suggestions welcome. How does dev3 work? dev3 implements VSH and, I would expect, needs `run_command`. Maybe I implemented the same thing for dev3, but called it something else? (VSH == Visual SHell). Process.py/generate_shell_components(...) creates and registers VSH components, and the actual instantiators/handlers are mostly in 0D/python/std/std.py. Furthermore, I am trying extending `generate_shell_components(...)` to create string-constant part automatically and am dropping the closing squote (') from string component names to make them work more like the VSH "$" components. In the newest version, 'RWR' will be called 'RWR (no closing squote).

**Comment by guitarvydas** [comment]
update: 0D/python/std/std.py contains code for `shell_out_handler` that is used by VSH. Maybe the above code for ohmjs needs to be completely revamped to use the lower-level std component `shell_out`. Off-hand, it looks like this could be done completely at the diagram level and the above code could be deleted. Further thinking required...

**Comment by RAbraham** [comment]
cool, let me know. It seems like code execution is not reaching this point (so that's why it's not erroring out). Is that what you expect if one runs `dev2` for e.g.?

**Comment by guitarvydas** [comment]
I think that dev2 works but uses some other code and doesn't error out. [Did I push this version yet?]

**Comment by RAbraham** [comment]
not sure. because I just pulled and I still see this error(I think you mentioned that you corrected it?)
<img width="774" alt="image" src="https://github.com/guitarvydas/0D/assets/214189/6309eace-cfd2-4086-bcf6-0285ea5a0c4b">

but after pulling, dev2 seems to be working! (to my naive eyes)
